### ISSUE TITLE
Crashing with Tailwind

### ISSUE THREAD

**Issue by magnusriga** [Ephem/rollup-plugin-preserve-directives#13]
When trying to import a .css file with the Tailwind @ rules, the following error is thrown:

>  [!] (plugin preserve-directives) SyntaxError: Unexpected character '@' (1:0)

**The module:**

```javascript
"use client";

import "../styles.css";

import styled from "styled-components";

const StyledNextLink = styled.div`
  color: red;
`;

export const Test = () => {
  return <StyledNextLink>{`Test`}</StyledNextLink>;
};
```

**The CSS file:**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

```

**The rollup.config.js:**

```javascript
import typescript from "@rollup/plugin-typescript";
import postcss from "rollup-plugin-postcss";
import autoprefixer from "autoprefixer";
import tailwindcss from "tailwindcss";

import tailwindConfig from './tailwind.config.js';
import preserveDirectives from 'rollup-plugin-preserve-directives';

import pkg from "./package.json" assert { type: "json" };

export default {
  external: [
    ...Object.keys(pkg.peerDependencies),
    ...Object.keys(pkg.dependencies || []),
    "react/jsx-runtime",
  ],
  input: "src/index.tsx",
  output: {
    // file: "dist/index.js",
    dir: "dist",
    preserveModules: true,
    format: "cjs",
    interop: "auto",
  },
  watch: {
    include: "src/**",
  },
  plugins: [
    preserveDirectives(),
    postcss({
      extensions: [".css", ".module.css"],
      plugins: [autoprefixer(), tailwindcss(tailwindConfig)],
    }),
    typescript({ include: "src/**/*.{js,ts,jsx,tsx}" }),
  ],
};
```

**Comment by Ephem** [comment]
Thanks for reporting this!

I've noticed that in some cases errors that does not actually stem from this plugin itself, but are the result of some other error perhaps related to missing configuration etc, are reported falesly as stemming from this plugin just because it happens to be the first one that tries to parse the files. This error looks a bit like that, so, if you remove this plugin, does the error persist, and do you get a better error message then?

(In these cases, this plugin seems to "swallow" errors and report a less detailed error message than the original, this is something I've been meaning to look into and should open a separate issue about.)

**Comment by magnusriga** [comment]
> Thanks for reporting this!
> 
> I've noticed that in some cases errors that does not actually stem from this plugin itself, but are the result of some other error perhaps related to missing configuration etc, are reported falesly as stemming from this plugin just because it happens to be the first one that tries to parse the files. This error looks a bit like that, so, if you remove this plugin, does the error persist, and do you get a better error message then?
> 
> (In these cases, this plugin seems to "swallow" errors and report a less detailed error message than the original, this is something I've been meaning to look into and should open a separate issue about.)

Hi Ephem. Indeed, removing the plugin eliminates that error (but reintroduces the 'use client' issue).

@Ephem Here is a minimal example that works if you add 'use client' manually to the relevant built components in dist (build the web app separately, so you do not overwrite the added 'use client':

https://github.com/magnusriga/rollup

**Comment by Ephem** [comment]
Thanks for checking! What happens if you put this plugin last instead of first in the plugin list? I just noticed postcss happened after this one. (Not sure it helps, might have to do something around the ast parsing, but would be helpful input.)

Just went on vacation so will try to look into this next week!

**Comment by magnusriga** [comment]
> Thanks for checking! What happens if you put this plugin last instead of first in the plugin list? I just noticed postcss happened after this one. (Not sure it helps, might have to do something around the ast parsing, but would be helpful input.)
> 
> Just went on vacation so will try to look into this next week!

Ah, fantastic. Moving it after postcss worked! Thanks a million!

**Comment by Ephem** [comment]
Great to hear! I made a note that I should add that to the docs. 🙏
